### ISSUE TITLE
Errors displayed on browser console for cluster page in OCM UI

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#671] opened 2020-04-29 10:37 UTC
This is probably not an issue on our side, but probably worth looked into it:

![console_error](https://user-images.githubusercontent.com/4579967/80586667-94959a00-8a15-11ea-9b9b-ecd1dd7e5f53.png)

**Comment by bond95** [comment] 2020-06-23 14:49
@tisnik which one do you mean? Because as far as I see, there is a few errors about bad webpack configuration (it's not our problem and it's better not to do anything with their webpack), and a few 400 request response (do we even have this code in aggregator?).

**Comment by bond95** [comment] 2020-06-23 15:13
@tisnik I don't see that error at all, I see next one and this one is not our issue
![image](https://user-images.githubusercontent.com/3332176/85421475-bffbb780-b574-11ea-92c8-55e24daf0bde.png)

**Comment by bond95** [comment] 2020-06-24 08:21
@tisnik could I close it?

**Comment by cben** [comment] 2020-06-24 12:49
Hi.  No idea what Insights project (if any) is root cause, but I've been seeing 2 errors in [OCM](https://cloud.redhat.com/openshift) console for a long time:

#### Chrome:
```
entry.js:233 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at entry.js:233
(anonymous) @ entry.js:257
Promise.catch (async)
C @ entry.js:257
(anonymous) @ chrome.js:33
Promise.then (async)
(anonymous) @ chrome.js:33
Promise.then (async)
parcelRequire.ZUGm.@babel/runtime/helpers/defineProperty @ chrome.js:33
f @ tooltip.css:1
parcelRequire.x3DH @ tooltip.css:1
(anonymous) @ tooltip.css:1
```
https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/entry.js#L233

```
actions.js:32 Uncaught (in promise) Error: unknown app identifier: openshift
    at Object.l [as identifyApp] (actions.js:32)
    at ReducerRegistry.js:16
    at entry.js:60
l @ actions.js:78
(anonymous) @ actions.js:78
(anonymous) @ entry.js:257
Promise.then (async)
identifyApp @ entry.js:257
(anonymous) @ Shield.js:373
n @ bundle.main.js?5a89d604285143ae6c9b:1
(anonymous) @ bundle.main.js?5a89d604285143ae6c9b:1
(anonymous) @ bundle.main.js?5a89d604285143ae6c9b:1
```
https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/redux/actions.js#L32

#### Firefox
```
TypeError: can't convert undefined to object chrome.js:721:6560
```

```
Error: unknown app identifier: openshift chrome.js:536:2027
```
no stack traces, probably related to various warnings about source maps :grin: but apparently same errors as Chrome.

**Comment by elad661** [comment] 2020-06-24 15:05
@bond95 
Any error coming from `chrome.js` is the responsibility of the Insights Platform and should be filed against their internal JIRA.  Not sure about the other errors. I suggest that if anything bothers you *and* it comes from OCM itself, you can file bugs against our JIRA so we can track and eventually fix them.

**Comment by bond95** [comment] 2020-06-25 09:16
Thank you @elad661 @cben . I there some link to their board?

**Comment by bond95** [comment] 2020-06-26 11:41
Created ticket in Cloud Services board https://projects.engineering.redhat.com/browse/RHCLOUD-7452

**Closed** 2020-06-26 12:35 UTC
Labels: UI, bug
