### ISSUE TITLE
"Last check: 1 day ago" seems wrong for connected clusters

### ISSUE THREAD

**Issue by radekvokal** [RedHatInsights/insights-results-aggregator#616] opened 2020-04-23 09:25 UTC
I'm looking at
Cluster ID
    fdcc5560-1090-46b8-b6d4-adf4880d2452

The cluster is connected, reporting that monitoring data was uploaded 2 hours ago. Insights data is not more than couple hours old. Yet the cluster reports that analysis was done 1 day ago. This looks like a bug to me 

![new-screenshot](https://user-images.githubusercontent.com/2545481/80082467-b7770880-8554-11ea-9ac8-c0a6f2ef7a9b.png)

**Comment by Sergey1011010** [comment] 2020-05-14 10:49
@radekvokal looks like the issue is fixed. Could you please check?

**Comment by Sergey1011010** [comment] 2020-05-18 09:54
Close since it was fixed in one of previous PRs

**Closed by Sergey1011010** 2020-05-18 09:54 UTC
Labels: bug
