### ISSUE TITLE
Benchmarks for consumer part

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#184] opened 2020-02-28 12:28 UTC
As a developer I want to be able to run benchmarks that checks durability of consumer part of the aggregator application.

**Comment by Sergey1011010** [comment] 2020-04-28 09:22
isn't it duplicate of https://github.com/RedHatInsights/insights-results-aggregator/issues/638?

**Comment by Sergey1011010** [comment] 2020-05-20 12:54
Done by https://github.com/RedHatInsights/insights-results-aggregator/pull/640

**Closed by Sergey1011010** 2020-05-20 12:54 UTC
Labels: benchmarks, enhancement, user story
